### ISSUE TITLE
Camera panning gives weird object offset

### ISSUE THREAD

**Issue by tntmeijs** [TeamWisp/Maya-Ray-Traced-Viewport-Plugin#18]
Try panning the camera. The grid and the object will not be aligned anymore.

**Comment by tntmeijs** [comment]
Update: this might be caused by the mismatch in viewport <--> wisp framebuffer dimensions. Adding a resize feature might resolve this issue.

**Comment by MeineZ** [comment]
Relevant to issue #33 and fixed by PR #53
