### ISSUE TITLE
Maya shut-down fails

### ISSUE THREAD

**Issue by tntmeijs** [TeamWisp/Maya-Ray-Traced-Viewport-Plugin#4]
While the Wisp renderer can get initialized and destroyed properly via the plug-in, there is an edge case. If the user decides to shut-down Maya without unloading the plug-in, Maya will fail to completely shut-down.

A small window pops up and the editor becomes unresponsive.

Maya does seem to save files just fine, so did not break at all. It is purely the shut-down phase.
![maya_shutdown_bug](https://user-images.githubusercontent.com/15856620/49373617-fce82b00-f6fe-11e8-8392-d3452deb1d9e.gif)

**Comment by tntmeijs** [comment]
Currently working on this.
The plug-in can be unloaded once now but crashes when reloading it a second time.

**Comment by MeineZ** [comment]
Fixed it in [this](https://github.com/TeamWisp/WispRenderer/pull/308) WispRenderer PR
