### ISSUE TITLE
Model translation does not take parent-child relationship into account

### ISSUE THREAD

**Issue by tntmeijs** [TeamWisp/Maya-Ray-Traced-Viewport-Plugin#40]
**Describe the bug**
When moving a child object, the transform does not get updated correctly. I suspect this is because we do not use the parent transform while calculating the object position.

**To Reproduce**
1. Open Maya and load a model with a somewhat complex hierarchy.
2. Move one of the child objects around.
3. Check the location of the Maya overlay, it's misaligned now.

**Expected behavior**
I would expect the model to keep stay lined up with the overlay.

**Screenshots**
![image](https://user-images.githubusercontent.com/15856620/55160353-69ca7980-5163-11e9-9514-5c46e183d454.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version: Maya 2019

**Comment by MeineZ** [comment]
This issue has been resolved a while ago. Although, rotations don't work as of right now, so I'll keep it open for now.

**Comment by MeineZ** [comment]
This issue has been resolved completely now by #81
