### ISSUE TITLE
Importing models must happen in Maya Viewport

### ISSUE THREAD

**Issue by MeineZ** [TeamWisp/Maya-Ray-Traced-Viewport-Plugin#47]
**Describe the bug**
The textures are not properly loaded when importing models and the Wisp renderer is active in a viewport. To properly load these textures, import the model when the Wisp renderer is not active in any viewport (it can already be loaded though).

**To Reproduce**
1. Load Wisp renderer
2. Open Wisp renderer in the Maya viewport
3. Import a model
4. See black textures

**Expected behavior**
The proper textures and proper change callbacks.
To reproduce expected behavior:
1. Load Wisp renderer
2. Import a model
3. Open Textured View
4. Open Wisp renderer in the Maya viewport
5. See textures

**Screenshots**
[![Screenshot from Gyazo](https://gyazo.com/40bdaba7f70fc5bece41d3f0c7d7592a/raw)](https://gyazo.com/40bdaba7f70fc5bece41d3f0c7d7592a)

**Comment by tntmeijs** [comment]
Current version of the plug-in fails to import models.

**Comment by MeineZ** [comment]
The plug-in crashes because it tries to read the tangents from the mesh, even though these are not created/loaded/available in the mesh data that is received from the Maya API.

After the first time that you detect missing tangents or another vertex attribute list, Maya calls an update callback on the mesh. That second callback **does** contain the missing vertex attribute list(s).

**Comment by MeineZ** [comment]
This issue is fixed by #108
