### ISSUE TITLE
Maya freezes on empty scene with RTX

### ISSUE THREAD

**Issue by tntmeijs** [TeamWisp/Maya-Ray-Traced-Viewport-Plugin#94]
Maya 2018 freezes when loading Wisp in an empty scene.

I suspect that this may have something to do with the recent "feature_as" merge into the Wisp rendering framework.

Steps to reproduce:
1) Open Maya.
2) Load Wisp.
3) Switch to the Wisp viewport.

System specifications:
- Intel Core i5 9400F
- GIGABYTE Geforce RTX 2060 Mini ITX
- 16 GB DDR4-2600MHz RAM 
- Maya on SSD

**Comment by MeineZ** [comment]
This issue is fixed since the latest WispRenderer dependency update.
